-- For adding black and white nonograms that reward more than 2000 XP use "Module:Data/XP_nonograms_bw".
-- If a name uses double quotes use a forward slash (e.g. "The "Z letter" -> "The \"Z\" letter").
		
-------------------------- ONLY BASE XP FROM NONOGRAMS! -------------------------- 
----------- (Without any bonuses, like Sushi, Date cake, skills, etc.) -----------

return {
	{
		link            = "[#145125:Tiger]",
		author          = "AJ7411",
		xp              = "1894",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#159326:Bachira]",
		author          = "the agreste",
		xp              = "1947",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Sport",
		puzzle_type     = "2",
	},
	{
		link            = "[#78292:(Aang,Kora)]",
		author          = "kristalaks",
		xp              = "1910",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Symbols",
		puzzle_type     = "2",
	},
	{
		link            = "[#43052:Pirate's ship]",
		author          = "Undrick",
		xp              = "1933",
		size            = "80x80",
		category_1      = "Pirates",
		category_2      = "Ships",
		puzzle_type     = "3",
	},
	{
		link            = "[#164509:Cat in a package]",
		author          = "Lisenok_chiffa",
		xp              = "1939",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#167860:Fantasy bow]",
		author          = "nanopsae",
		xp              = "1977",
		size            = "75x79",
		category_1      = "Fantasy",
		category_2      = "Weapons",
		puzzle_type     = "2",
	},
	{
		link            = "[#169346:Turtle]",
		author          = "AJ7411",
		xp              = "1848",
		size            = "80x80",
		category_1      = "Fish",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#169618:Mountains]",
		author          = "Giannis",
		xp              = "1914",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#19570:Flirt]",
		author          = "Street Fighter",
		xp              = "1922",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#147755:Bird 4]",
		author          = "AJ7411",
		xp              = "1962",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#169917:Av]",
		author          = "arti4ever",
		xp              = "1877",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#102067:bear]",
		author          = "chibis",
		xp              = "1941",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#45943:Conestoga wagon]",
		author          = "Alexroma5",
		xp              = "1911",
		size            = "80x80",
		category_1      = "Transport",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#10956:Leopard]",
		author          = "belko61",
		xp              = "1851",
		size            = "80x65",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#37008:lion]",
		author          = "Alexroma5",
		xp              = "1929",
		size            = "80x70",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#145575:Animal]",
		author          = "AJ7411",
		xp              = "1971",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#117574:Great Tit]",
		author          = "Dogiuks",
		xp              = "1951",
		size            = "80x70",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#140213:Violet Evergarden]",
		author          = "rphii",
		xp              = "1919",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#122220:House by the river]",
		author          = "Claireskee",
		xp              = "1884",
		size            = "75x70",
		category_1      = "Nature",
		category_2      = "Houses",
		puzzle_type     = "3",
	},
	{
		link            = "[#122121:Constellations in Stars]",
		author          = "Scarheart",
		xp              = "1873",
		size            = "70x70",
		category_1      = "Space",
		category_2      = "Horoscope",
		puzzle_type     = "3",
	},
	{
		link            = "[#103321:Biang]",
		author          = "Hugo Carneiro",
		xp              = "1923",
		size            = "80x80",
		category_1      = "Painting",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#200781:Black Dream Catcher]",
		author          = "Jan Kokto",
		xp              = "1845",
		size            = "75x80",
		category_1      = "Horoscope",
		category_2      = "Objects",
		puzzle_type     = "3",
	},
	{
		link            = "[#201465:Cat's eye. Mark]",
		author          = "Jan Kokto",
		xp              = "1973",
		size            = "70x70",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#172814:A luxuriant tree]",
		author          = "Turkish_123",
		xp              = "1897",
		size            = "79x74",
		category_1      = "Plants",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#193295:One day I'm going to go crazy]",
		author          = "Jan Kokto",
		xp              = "1966",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Japan",
		puzzle_type     = "2",
	},
	{
		link            = "[#207509:Rhinoceros]",
		author          = "yagr",
		xp              = "1989",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#208948:The Beagle]",
		author          = "yagr",
		xp              = "1919",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#45889:Dragon Girl]",
		author          = "LUNA-CROIX",
		xp              = "1929",
		size            = "60x80",
		category_1      = "Kawaii",
		category_2      = "Anime",
		puzzle_type     = "2",
	},
	{
		link            = "[#135670:Beethoven]",
		author          = "the agreste",
		xp              = "1845",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Music",
		puzzle_type     = "3",
	},
	{
		link            = "[#182274:Highland cattle]",
		author          = "iltarusko",
		xp              = "1930",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#147393:Animal]",
		author          = "AJ7411",
		xp              = "1941",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#190637:with butterfly]",
		author          = "Dimsum",
		xp              = "1971",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#169615:WaterMelon]",
		author          = "Ap6y3",
		xp              = "1859",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#232135:Viper]",
		author          = "ChefSloth",
		xp              = "1987",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#232634:Octo cocosini]",
		author          = "Oceanofharmony",
		xp              = "1929",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Games",
		puzzle_type     = "2",
	},
	{
		link            = "[#106540:Buffalo]",
		author          = "chibis",
		xp              = "1803",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#87144:Donkey in the medow]",
		author          = "Malgoska",
		xp              = "1808",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Nature",
		puzzle_type     = "3",
	},
	{
		link            = "[#28377:Woman consumed by darkness]",
		author          = "Nomen Nescio",
		xp              = "1812",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "People",
		puzzle_type     = "3",
	},
	{
		link            = "[#118007:house in the woods]",
		author          = "chibis",
		xp              = "1976",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Houses",
		puzzle_type     = "1",
	},
	{
		link            = "[#75697:Gaerea Sigil]",
		author          = "TheComet811",
		xp              = "1822",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "Music",
		puzzle_type     = "3",
	},
	{
		link            = "[#149313:Flower 2]",
		author          = "AJ7411",
		xp              = "1806",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#162278:Ouroboros]",
		author          = "AshenThrone",
		xp              = "1990",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Designs",
		puzzle_type     = "2",
	},
	{
		link            = "[#148044:Scorpion]",
		author          = "AJ7411",
		xp              = "1729",
		size            = "80x80",
		category_1      = "Insects",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#157383:Panda]",
		author          = "AJ7411",
		xp              = "1443",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#157342:Pig]",
		author          = "AJ7411",
		xp              = "1592",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#158707:Abstract Spiral]",
		author          = "Mushroom-World",
		xp              = "1071",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#153450:Boxes 4]",
		author          = "Tapehead",
		xp              = "1979",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#131232:Old wine cellar]",
		author          = "belko61",
		xp              = "1969",
		size            = "70x80",
		category_1      = "Food",
		category_2      = "Objects",
		puzzle_type     = "4",
	},
	{
		link            = "[#157842:Squares]",
		author          = "Nomase",
		xp              = "1962",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#102787:Squirrel]",
		author          = "belko61",
		xp              = "1955",
		size            = "70x70",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#151021:Bikini 4]",
		author          = "AJ7411",
		xp              = "1531",
		size            = "80x68",
		category_1      = "Clothes",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#175588:Lille's bulldog]",
		author          = "Ahmad Hisham",
		xp              = "1078",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#202359:Octopus]",
		author          = "Mike1955",
		xp              = "1920",
		size            = "80x80",
		category_1      = "Fish",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#87290:CHUNITHM\"DJ-MEGA\"]",
		author          = "KSK_Shizuno",
		xp              = "1797",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "3",
	},
	{
		link            = "[#201822:Captain]",
		author          = "Mike1955",
		xp              = "1955",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Ships",
		puzzle_type     = "1",
	},
	{
		link            = "[#207346:lion]",
		author          = "yagr",
		xp              = "1725",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#209698:Primrose]",
		author          = "Mike1955",
		xp              = "1777",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#209024:Abstract mask]",
		author          = "Mike1955",
		xp              = "1809",
		size            = "80x80",
		category_1      = "Painting",
		category_2      = "Objects",
		puzzle_type     = "1",
	},
	{
		link            = "[#211439:Tractor]",
		author          = "Mike1955",
		xp              = "1708",
		size            = "80x80",
		category_1      = "Machines",
		category_2      = "Transport",
		puzzle_type     = "1",
	},
	{
		link            = "[#206991:Bird]",
		author          = "AJ7411",
		xp              = "1544",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "Symbols",
		puzzle_type     = "1",
	},
	{
		link            = "[#210375:Machinery doodle]",
		author          = "Mike1955",
		xp              = "1427",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "Machines",
		puzzle_type     = "1",
	},
	{
		link            = "[#208003:Cologne Cathedral]",
		author          = "Erllendur",
		xp              = "1843",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#207215:Satellite]",
		author          = "Mike1955",
		xp              = "1508",
		size            = "80x80",
		category_1      = "Space",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#210340:Sam Carter]",
		author          = "Late555",
		xp              = "1653",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "People",
		puzzle_type     = "1",
	},
	{
		link            = "[#211282:Cat head deco b&w]",
		author          = "Mike1955",
		xp              = "1195",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "Designs",
		puzzle_type     = "1",
	},
	{
		link            = "[#211129:An Eurasian magpie (Pica Pica)]",
		author          = "artbyROO",
		xp              = "1806",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#93438:Japanese]",
		author          = "belko61",
		xp              = "1926",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Japan",
		puzzle_type     = "1",
	},
	{
		link            = "[#93428:Red Deer]",
		author          = "belko61",
		xp              = "1880",
		size            = "65x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	-- Placeholder.
	{
		link            = "",
		author          = "",
		xp              = "",
		new_xp          = "",
		size            = "",
		category_1      = "",
		category_2      = "",
		puzzle_type     = "",
	},
}
