
	{
		link            = "[#248559:Maximalist 24 - Shades of blue]",
		author          = "gattaccia",
		xp              = "",
		new_xp          = "3064",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#248576:Sloth]",
		author          = "Ira",
		xp              = "",
		new_xp          = "3000",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Photorealism",
		puzzle_type     = "3",
	},
	{
		link            = "[#248651:A very boo vacation]",
		author          = "Bella_brie",
		xp              = "",
		new_xp          = "3923",
		size            = "77x80",
		category_1      = "Unreal",
		category_2      = "Holidays",
		puzzle_type     = "2",
	},
	{
		link            = "[#248569:Neon balloon]",
		author          = "Bella_brie",
		xp              = "",
		new_xp          = "3955",
		size            = "75x78",
		category_1      = "Kawaii",
		category_2      = "Games",
		puzzle_type     = "3",
	},
	{
		link            = "[#248513:Miscellaneous patterns 49]",
		author          = "SOP",
		xp              = "",
		new_xp          = "3473",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#247818:Split decision]",
		author          = "bill777",
		xp              = "",
		new_xp          = "3839",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Fish",
		puzzle_type     = "4",
	},
	{
		link            = "[#248152:In a sea of souls]",
		author          = "Acronym Tine",
		xp              = "",
		new_xp          = "3408",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Fish",
		puzzle_type     = "3",
	},
	{
		link            = "[#247628:Arachnicraft]",
		author          = "bill777",
		xp              = "",
		new_xp          = "3766",
		size            = "80x75",
		category_1      = "Fiction",
		category_2      = "Insects",
		puzzle_type     = "4",
	},
	{
		link            = "[#248182:Pipe Dream]",
		author          = "Rangoon",
		xp              = "",
		new_xp          = "3753",
		size            = "80x78",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#248749:Raccoon with berries]",
		author          = "Ira",
		xp              = "",
		new_xp          = "4025",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Photorealism",
		puzzle_type     = "3",
	},
	{
		link            = "[#247985:Fin and tonic]",
		author          = "bill777",
		xp              = "",
		new_xp          = "4148",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Fish",
		puzzle_type     = "4",
	},
	{
		link            = "[#247526:Crossfire]",
		author          = "bill777",
		xp              = "",
		new_xp          = "3769",
		size            = "80x75",
		category_1      = "Fantasy",
		category_2      = "Animals",
		puzzle_type     = "4",
	},
	{
		link            = "[#248401:Flower field]",
		author          = "BamaBarb",
		xp              = "",
		new_xp          = "3772",
		size            = "80x80",
		category_1      = "Insects",
		category_2      = "Flowers",
		puzzle_type     = "3",
	},
	{
		link            = "[#248879:Kinkajou the Rainwing]",
		author          = "Acronym Tine",
		xp              = "",
		new_xp          = "3855",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#248878:Hot property]",
		author          = "bill777",
		xp              = "",
		new_xp          = "3609",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#247868:Bogsquatch]",
		author          = "bill777",
		xp              = "",
		new_xp          = "3316",
		size            = "70x80",
		category_1      = "Unreal",
		category_2      = "Games",
		puzzle_type     = "4",
	},
	{
		link            = "[#248475:Roary McRoarface]",
		author          = "bill777",
		xp              = "",
		new_xp          = "4757",
		size            = "80x75",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#248575:African elephant]",
		author          = "Ira",
		xp              = "",
		new_xp          = "3315",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Photorealism",
		puzzle_type     = "3",
	},